name: Run Js script

on:
  push:
    branches:
    - main

env:
  client_id: ${{ secrets.CLIENT_ID }}
  
jobs:
  my-job:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
      - uses: actions/checkout@v1
          
      - name: Setup Js
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      - name: npm install, build, and test
      - run: |
          npm install
          npm run build --if-present
          npm test
          node test.js
          
