name: Run Js script

on:
  push:
    branches:
    - main

env:
  API_KEY: ${{ secrets.API_KEY }}
  
jobs:
  my-job:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.1
          
      - name: Setup Js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '14'
      
      - name: npm install, build, and test
        run:
          node crazy
          
          
        # node 'test.js'
        # npm install
        # node ../test.js
          
          

